name: Update actions-toolbox
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of actions-toolbox we are updating to'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          always-auth: true
          registry-url: ${{ secrets.ACTIONS_NEXUS_NPM_ENDPOINT }}
      - name: Set npm auth
        run: npm config set _auth "${{ secrets.ACTIONS_NEXUS_NPM_READ_TOKEN }}"
      - name: npm install
        run: npm install
      - name: Upgrade actions-toolbox
        run: |
          yarn add @wealthsimple/actions-toolbox@${{ github.event.inputs.version }}
      - name: Commit latest actions-toolbox
        run: |
          git add yarn.lock package.json
          git commit -m "feat(release):Update actions-toolbox to ${{ github.event.inputs.version }}"
          git push
